Repository sendsmaily/sendsmaily-wordpress-plugin, pull requests merged in 2021-07, with the labels that each got.

#113 Update contribution guide
  .github/pull_request_template.md
  CONTRIBUTING.md
  includes/class-smaily-for-wp-lifecycle.php
  migrations/upgrade-3-0-0.php
Labels: documentation, maintenance

#115 WordPress 5.8 compatibility tested
  readme.txt
Labels: maintenance

#117 Release 3.0.5 checklist changes
  CHANGELOG.md
  assets/screenshot-3.png
  assets/screenshot-4.png
  assets/screenshot-5.png
  assets/screenshot-6.png
  lang/smaily-for-wp-et.mo
  lang/smaily-for-wp-et.po
  lang/smaily-for-wp.pot
  readme.txt
  smaily-for-wp.php
Labels: documentation, maintenance

#116 3.0.5 release
  CHANGELOG.md
  assets/screenshot-3.png
  assets/screenshot-4.png
  assets/screenshot-5.png
  assets/screenshot-6.png
  lang/smaily-for-wp-et.mo
  lang/smaily-for-wp-et.po
  lang/smaily-for-wp.pot
  readme.txt
  smaily-for-wp.php
Labels: release
