Repository sendsmaily/sendsmaily-wordpress-plugin, pull requests merged in 2021-03, with the labels that each got.

#94 Fix advanced form
  admin/class-smaily-for-wp-admin.php
  admin/partials/smaily-for-wp-admin-form.php
  includes/class-smaily-for-wp-options.php
  includes/class-smaily-for-wp-widget.php
  public/partials/smaily-for-wp-public-advanced.php
Labels: bug

#93 3.0.0 release
  CHANGELOG.md
  action.php
  admin/class-smaily-for-wp-admin.php
  admin/css/smaily-for-wp-admin.css
  admin/index.php
  admin/js/smaily-for-wp-admin.js
  admin/partials/smaily-for-wp-admin-form.php
  admin/partials/smaily-for-wp-admin-page.php
  code/Request.php
  docker-compose.yml
  html/form/advanced.php
  includes/activator.php
  includes/class-smaily-for-wp-i18n.php
  includes/class-smaily-for-wp-lifecycle.php
  includes/class-smaily-for-wp-loader.php
  includes/class-smaily-for-wp-options.php
  includes/class-smaily-for-wp-request.php
  includes/class-smaily-for-wp-template.php
  includes/class-smaily-for-wp-widget.php
  includes/class-smaily-for-wp.php
  includes/index.php
  index.php
  lang/smaily-for-wp-et.mo
  lang/smaily-for-wp-et.po
  lang/smaily-for-wp.pot
  migrations/index.php
  migrations/upgrade-3_0_0.php
  public/class-smaily-for-wp-public.php
  public/index.php
  public/partials/smaily-for-wp-public-advanced.php
  public/partials/smaily-for-wp-public-basic.php
  readme.txt
  smaily-for-wp.php
  uninstall.php
Labels: release

#96 Fix plugin stable tag to 3.0.0
  readme.txt
Labels: maintenance, release

#97 Update admin and widget settings screenshots
  assets/screenshot-2.png
  assets/screenshot-3.png
Labels: maintenance

#99 Fix plugin name in development and production differ
  admin/class-smaily-for-wp-admin.php
  docker-compose.yml
  includes/class-smaily-for-wp.php
Labels: bug

#101 Release 3.0.1 checklist changes
  CHANGELOG.md
  readme.txt
  smaily-for-wp.php
Labels: release

#100 Release 3.0.1
  CHANGELOG.md
  admin/class-smaily-for-wp-admin.php
  docker-compose.yml
  includes/class-smaily-for-wp.php
  readme.txt
  smaily-for-wp.php
Labels: release

#102 Remove unnecessary static content limiting
  admin/class-smaily-for-wp-admin.php
Labels: bug

#104 Release 3.0.2 checklist changes
  CHANGELOG.md
  readme.txt
  smaily-for-wp.php
Labels: release

#103 Release 3.0.2
  CHANGELOG.md
  admin/class-smaily-for-wp-admin.php
  readme.txt
  smaily-for-wp.php
Labels: release

#107 Release 3.0.3 checklist changes
  CHANGELOG.md
  readme.txt
  smaily-for-wp.php
Labels: documentation, maintenance

#106 3.0.3 release
  CHANGELOG.md
  readme.txt
  smaily-for-wp.php
Labels: release

#108 Fix advanced form when using shortcode
  public/class-smaily-for-wp-public.php
Labels: bug

#110 Release 3.0.4 checklist changes
  CHANGELOG.md
  readme.txt
  smaily-for-wp.php
Labels: documentation, maintenance

#109 3.0.4 release
  CHANGELOG.md
  public/class-smaily-for-wp-public.php
  readme.txt
  smaily-for-wp.php
Labels: release
